// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: scalezillapb/requests.proto

package scalezillapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scalezilla_ServicePortsDiscovery_FullMethodName = "/scalezillapb.Scalezilla/ServicePortsDiscovery"
	Scalezilla_ServiceNodePolling_FullMethodName    = "/scalezillapb.Scalezilla/ServiceNodePolling"
)

// ScalezillaClient is the client API for Scalezilla service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScalezillaClient interface {
	ServicePortsDiscovery(ctx context.Context, in *ServicePortsDiscoveryRequestReply, opts ...grpc.CallOption) (*ServicePortsDiscoveryRequestReply, error)
	ServiceNodePolling(ctx context.Context, in *ServiceNodePollingRequestReply, opts ...grpc.CallOption) (*ServiceNodePollingRequestReply, error)
}

type scalezillaClient struct {
	cc grpc.ClientConnInterface
}

func NewScalezillaClient(cc grpc.ClientConnInterface) ScalezillaClient {
	return &scalezillaClient{cc}
}

func (c *scalezillaClient) ServicePortsDiscovery(ctx context.Context, in *ServicePortsDiscoveryRequestReply, opts ...grpc.CallOption) (*ServicePortsDiscoveryRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicePortsDiscoveryRequestReply)
	err := c.cc.Invoke(ctx, Scalezilla_ServicePortsDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scalezillaClient) ServiceNodePolling(ctx context.Context, in *ServiceNodePollingRequestReply, opts ...grpc.CallOption) (*ServiceNodePollingRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceNodePollingRequestReply)
	err := c.cc.Invoke(ctx, Scalezilla_ServiceNodePolling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScalezillaServer is the server API for Scalezilla service.
// All implementations must embed UnimplementedScalezillaServer
// for forward compatibility.
type ScalezillaServer interface {
	ServicePortsDiscovery(context.Context, *ServicePortsDiscoveryRequestReply) (*ServicePortsDiscoveryRequestReply, error)
	ServiceNodePolling(context.Context, *ServiceNodePollingRequestReply) (*ServiceNodePollingRequestReply, error)
	mustEmbedUnimplementedScalezillaServer()
}

// UnimplementedScalezillaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScalezillaServer struct{}

func (UnimplementedScalezillaServer) ServicePortsDiscovery(context.Context, *ServicePortsDiscoveryRequestReply) (*ServicePortsDiscoveryRequestReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ServicePortsDiscovery not implemented")
}
func (UnimplementedScalezillaServer) ServiceNodePolling(context.Context, *ServiceNodePollingRequestReply) (*ServiceNodePollingRequestReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ServiceNodePolling not implemented")
}
func (UnimplementedScalezillaServer) mustEmbedUnimplementedScalezillaServer() {}
func (UnimplementedScalezillaServer) testEmbeddedByValue()                    {}

// UnsafeScalezillaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScalezillaServer will
// result in compilation errors.
type UnsafeScalezillaServer interface {
	mustEmbedUnimplementedScalezillaServer()
}

func RegisterScalezillaServer(s grpc.ServiceRegistrar, srv ScalezillaServer) {
	// If the following call panics, it indicates UnimplementedScalezillaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scalezilla_ServiceDesc, srv)
}

func _Scalezilla_ServicePortsDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicePortsDiscoveryRequestReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalezillaServer).ServicePortsDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scalezilla_ServicePortsDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalezillaServer).ServicePortsDiscovery(ctx, req.(*ServicePortsDiscoveryRequestReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scalezilla_ServiceNodePolling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceNodePollingRequestReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalezillaServer).ServiceNodePolling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scalezilla_ServiceNodePolling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalezillaServer).ServiceNodePolling(ctx, req.(*ServiceNodePollingRequestReply))
	}
	return interceptor(ctx, in, info, handler)
}

// Scalezilla_ServiceDesc is the grpc.ServiceDesc for Scalezilla service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scalezilla_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scalezillapb.Scalezilla",
	HandlerType: (*ScalezillaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServicePortsDiscovery",
			Handler:    _Scalezilla_ServicePortsDiscovery_Handler,
		},
		{
			MethodName: "ServiceNodePolling",
			Handler:    _Scalezilla_ServiceNodePolling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalezillapb/requests.proto",
}
