// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: scalezillapb/requests.proto

package scalezillapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicePortsDiscoveryRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PortHttp      uint32                 `protobuf:"varint,3,opt,name=port_http,json=portHttp,proto3" json:"port_http,omitempty"`
	PortGrpc      uint32                 `protobuf:"varint,4,opt,name=port_grpc,json=portGrpc,proto3" json:"port_grpc,omitempty"`
	PortRaft      uint32                 `protobuf:"varint,5,opt,name=port_raft,json=portRaft,proto3" json:"port_raft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePortsDiscoveryRequestReply) Reset() {
	*x = ServicePortsDiscoveryRequestReply{}
	mi := &file_scalezillapb_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePortsDiscoveryRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePortsDiscoveryRequestReply) ProtoMessage() {}

func (x *ServicePortsDiscoveryRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_scalezillapb_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePortsDiscoveryRequestReply.ProtoReflect.Descriptor instead.
func (*ServicePortsDiscoveryRequestReply) Descriptor() ([]byte, []int) {
	return file_scalezillapb_requests_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePortsDiscoveryRequestReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServicePortsDiscoveryRequestReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServicePortsDiscoveryRequestReply) GetPortHttp() uint32 {
	if x != nil {
		return x.PortHttp
	}
	return 0
}

func (x *ServicePortsDiscoveryRequestReply) GetPortGrpc() uint32 {
	if x != nil {
		return x.PortGrpc
	}
	return 0
}

func (x *ServicePortsDiscoveryRequestReply) GetPortRaft() uint32 {
	if x != nil {
		return x.PortRaft
	}
	return 0
}

var File_scalezillapb_requests_proto protoreflect.FileDescriptor

const file_scalezillapb_requests_proto_rawDesc = "" +
	"\n" +
	"\x1bscalezillapb/requests.proto\x12\fscalezillapb\"\xa4\x01\n" +
	"!ServicePortsDiscoveryRequestReply\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tport_http\x18\x03 \x01(\rR\bportHttp\x12\x1b\n" +
	"\tport_grpc\x18\x04 \x01(\rR\bportGrpc\x12\x1b\n" +
	"\tport_raft\x18\x05 \x01(\rR\bportRaft2\x89\x01\n" +
	"\n" +
	"Scalezilla\x12{\n" +
	"\x15ServicePortsDiscovery\x12/.scalezillapb.ServicePortsDiscoveryRequestReply\x1a/.scalezillapb.ServicePortsDiscoveryRequestReply\"\x00B/Z-github.com/scalezilla/scalezilla/scalezillapbb\x06proto3"

var (
	file_scalezillapb_requests_proto_rawDescOnce sync.Once
	file_scalezillapb_requests_proto_rawDescData []byte
)

func file_scalezillapb_requests_proto_rawDescGZIP() []byte {
	file_scalezillapb_requests_proto_rawDescOnce.Do(func() {
		file_scalezillapb_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalezillapb_requests_proto_rawDesc), len(file_scalezillapb_requests_proto_rawDesc)))
	})
	return file_scalezillapb_requests_proto_rawDescData
}

var file_scalezillapb_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scalezillapb_requests_proto_goTypes = []any{
	(*ServicePortsDiscoveryRequestReply)(nil), // 0: scalezillapb.ServicePortsDiscoveryRequestReply
}
var file_scalezillapb_requests_proto_depIdxs = []int32{
	0, // 0: scalezillapb.Scalezilla.ServicePortsDiscovery:input_type -> scalezillapb.ServicePortsDiscoveryRequestReply
	0, // 1: scalezillapb.Scalezilla.ServicePortsDiscovery:output_type -> scalezillapb.ServicePortsDiscoveryRequestReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scalezillapb_requests_proto_init() }
func file_scalezillapb_requests_proto_init() {
	if File_scalezillapb_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalezillapb_requests_proto_rawDesc), len(file_scalezillapb_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalezillapb_requests_proto_goTypes,
		DependencyIndexes: file_scalezillapb_requests_proto_depIdxs,
		MessageInfos:      file_scalezillapb_requests_proto_msgTypes,
	}.Build()
	File_scalezillapb_requests_proto = out.File
	file_scalezillapb_requests_proto_goTypes = nil
	file_scalezillapb_requests_proto_depIdxs = nil
}
