// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: scalezillapb/requests.proto

package scalezillapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicePortsDiscoveryRequestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PortHttp      uint32                 `protobuf:"varint,3,opt,name=port_http,json=portHttp,proto3" json:"port_http,omitempty"`
	PortGrpc      uint32                 `protobuf:"varint,4,opt,name=port_grpc,json=portGrpc,proto3" json:"port_grpc,omitempty"`
	PortRaft      uint32                 `protobuf:"varint,5,opt,name=port_raft,json=portRaft,proto3" json:"port_raft,omitempty"`
	IsVoter       bool                   `protobuf:"varint,6,opt,name=is_voter,json=isVoter,proto3" json:"is_voter,omitempty"`
	NodePool      string                 `protobuf:"bytes,7,opt,name=node_pool,json=nodePool,proto3" json:"node_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePortsDiscoveryRequestReply) Reset() {
	*x = ServicePortsDiscoveryRequestReply{}
	mi := &file_scalezillapb_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePortsDiscoveryRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePortsDiscoveryRequestReply) ProtoMessage() {}

func (x *ServicePortsDiscoveryRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_scalezillapb_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePortsDiscoveryRequestReply.ProtoReflect.Descriptor instead.
func (*ServicePortsDiscoveryRequestReply) Descriptor() ([]byte, []int) {
	return file_scalezillapb_requests_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePortsDiscoveryRequestReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServicePortsDiscoveryRequestReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServicePortsDiscoveryRequestReply) GetPortHttp() uint32 {
	if x != nil {
		return x.PortHttp
	}
	return 0
}

func (x *ServicePortsDiscoveryRequestReply) GetPortGrpc() uint32 {
	if x != nil {
		return x.PortGrpc
	}
	return 0
}

func (x *ServicePortsDiscoveryRequestReply) GetPortRaft() uint32 {
	if x != nil {
		return x.PortRaft
	}
	return 0
}

func (x *ServicePortsDiscoveryRequestReply) GetIsVoter() bool {
	if x != nil {
		return x.IsVoter
	}
	return false
}

func (x *ServicePortsDiscoveryRequestReply) GetNodePool() string {
	if x != nil {
		return x.NodePool
	}
	return ""
}

type ServiceNodePollingRequestReply struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Address                string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id                     string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	OsName                 string                 `protobuf:"bytes,3,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	OsVendor               string                 `protobuf:"bytes,4,opt,name=os_vendor,json=osVendor,proto3" json:"os_vendor,omitempty"`
	OsVersion              string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsFamily               string                 `protobuf:"bytes,6,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	OsHostname             string                 `protobuf:"bytes,7,opt,name=os_hostname,json=osHostname,proto3" json:"os_hostname,omitempty"`
	OsArchitecture         string                 `protobuf:"bytes,8,opt,name=os_architecture,json=osArchitecture,proto3" json:"os_architecture,omitempty"`
	OsType                 string                 `protobuf:"bytes,9,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	CpuTotal               uint32                 `protobuf:"varint,10,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuCores               uint32                 `protobuf:"varint,11,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuFrequency           float32                `protobuf:"fixed32,12,opt,name=cpu_frequency,json=cpuFrequency,proto3" json:"cpu_frequency,omitempty"`
	CpuCumulativeFrequency float64                `protobuf:"fixed64,13,opt,name=cpu_cumulative_frequency,json=cpuCumulativeFrequency,proto3" json:"cpu_cumulative_frequency,omitempty"`
	CpuCapabilitites       []string               `protobuf:"bytes,14,rep,name=cpu_capabilitites,json=cpuCapabilitites,proto3" json:"cpu_capabilitites,omitempty"`
	CpuVendor              string                 `protobuf:"bytes,15,opt,name=cpu_vendor,json=cpuVendor,proto3" json:"cpu_vendor,omitempty"`
	CpuModel               string                 `protobuf:"bytes,16,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	MemoryTotal            uint64                 `protobuf:"varint,17,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryAvailable        uint64                 `protobuf:"varint,18,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	Metadata               map[string]string      `protobuf:"bytes,19,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceNodePollingRequestReply) Reset() {
	*x = ServiceNodePollingRequestReply{}
	mi := &file_scalezillapb_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNodePollingRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodePollingRequestReply) ProtoMessage() {}

func (x *ServiceNodePollingRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_scalezillapb_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodePollingRequestReply.ProtoReflect.Descriptor instead.
func (*ServiceNodePollingRequestReply) Descriptor() ([]byte, []int) {
	return file_scalezillapb_requests_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceNodePollingRequestReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsVendor() string {
	if x != nil {
		return x.OsVendor
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsHostname() string {
	if x != nil {
		return x.OsHostname
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsArchitecture() string {
	if x != nil {
		return x.OsArchitecture
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetCpuTotal() uint32 {
	if x != nil {
		return x.CpuTotal
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetCpuFrequency() float32 {
	if x != nil {
		return x.CpuFrequency
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetCpuCumulativeFrequency() float64 {
	if x != nil {
		return x.CpuCumulativeFrequency
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetCpuCapabilitites() []string {
	if x != nil {
		return x.CpuCapabilitites
	}
	return nil
}

func (x *ServiceNodePollingRequestReply) GetCpuVendor() string {
	if x != nil {
		return x.CpuVendor
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *ServiceNodePollingRequestReply) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *ServiceNodePollingRequestReply) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_scalezillapb_requests_proto protoreflect.FileDescriptor

const file_scalezillapb_requests_proto_rawDesc = "" +
	"\n" +
	"\x1bscalezillapb/requests.proto\x12\fscalezillapb\"\xdc\x01\n" +
	"!ServicePortsDiscoveryRequestReply\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tport_http\x18\x03 \x01(\rR\bportHttp\x12\x1b\n" +
	"\tport_grpc\x18\x04 \x01(\rR\bportGrpc\x12\x1b\n" +
	"\tport_raft\x18\x05 \x01(\rR\bportRaft\x12\x19\n" +
	"\bis_voter\x18\x06 \x01(\bR\aisVoter\x12\x1b\n" +
	"\tnode_pool\x18\a \x01(\tR\bnodePool\"\x84\x06\n" +
	"\x1eServiceNodePollingRequestReply\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\aos_name\x18\x03 \x01(\tR\x06osName\x12\x1b\n" +
	"\tos_vendor\x18\x04 \x01(\tR\bosVendor\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x1b\n" +
	"\tos_family\x18\x06 \x01(\tR\bosFamily\x12\x1f\n" +
	"\vos_hostname\x18\a \x01(\tR\n" +
	"osHostname\x12'\n" +
	"\x0fos_architecture\x18\b \x01(\tR\x0eosArchitecture\x12\x17\n" +
	"\aos_type\x18\t \x01(\tR\x06osType\x12\x1b\n" +
	"\tcpu_total\x18\n" +
	" \x01(\rR\bcpuTotal\x12\x1b\n" +
	"\tcpu_cores\x18\v \x01(\rR\bcpuCores\x12#\n" +
	"\rcpu_frequency\x18\f \x01(\x02R\fcpuFrequency\x128\n" +
	"\x18cpu_cumulative_frequency\x18\r \x01(\x01R\x16cpuCumulativeFrequency\x12+\n" +
	"\x11cpu_capabilitites\x18\x0e \x03(\tR\x10cpuCapabilitites\x12\x1d\n" +
	"\n" +
	"cpu_vendor\x18\x0f \x01(\tR\tcpuVendor\x12\x1b\n" +
	"\tcpu_model\x18\x10 \x01(\tR\bcpuModel\x12!\n" +
	"\fmemory_total\x18\x11 \x01(\x04R\vmemoryTotal\x12)\n" +
	"\x10memory_available\x18\x12 \x01(\x04R\x0fmemoryAvailable\x12V\n" +
	"\bmetadata\x18\x13 \x03(\v2:.scalezillapb.ServiceNodePollingRequestReply.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfd\x01\n" +
	"\n" +
	"Scalezilla\x12{\n" +
	"\x15ServicePortsDiscovery\x12/.scalezillapb.ServicePortsDiscoveryRequestReply\x1a/.scalezillapb.ServicePortsDiscoveryRequestReply\"\x00\x12r\n" +
	"\x12ServiceNodePolling\x12,.scalezillapb.ServiceNodePollingRequestReply\x1a,.scalezillapb.ServiceNodePollingRequestReply\"\x00B/Z-github.com/scalezilla/scalezilla/scalezillapbb\x06proto3"

var (
	file_scalezillapb_requests_proto_rawDescOnce sync.Once
	file_scalezillapb_requests_proto_rawDescData []byte
)

func file_scalezillapb_requests_proto_rawDescGZIP() []byte {
	file_scalezillapb_requests_proto_rawDescOnce.Do(func() {
		file_scalezillapb_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalezillapb_requests_proto_rawDesc), len(file_scalezillapb_requests_proto_rawDesc)))
	})
	return file_scalezillapb_requests_proto_rawDescData
}

var file_scalezillapb_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scalezillapb_requests_proto_goTypes = []any{
	(*ServicePortsDiscoveryRequestReply)(nil), // 0: scalezillapb.ServicePortsDiscoveryRequestReply
	(*ServiceNodePollingRequestReply)(nil),    // 1: scalezillapb.ServiceNodePollingRequestReply
	nil,                                       // 2: scalezillapb.ServiceNodePollingRequestReply.MetadataEntry
}
var file_scalezillapb_requests_proto_depIdxs = []int32{
	2, // 0: scalezillapb.ServiceNodePollingRequestReply.metadata:type_name -> scalezillapb.ServiceNodePollingRequestReply.MetadataEntry
	0, // 1: scalezillapb.Scalezilla.ServicePortsDiscovery:input_type -> scalezillapb.ServicePortsDiscoveryRequestReply
	1, // 2: scalezillapb.Scalezilla.ServiceNodePolling:input_type -> scalezillapb.ServiceNodePollingRequestReply
	0, // 3: scalezillapb.Scalezilla.ServicePortsDiscovery:output_type -> scalezillapb.ServicePortsDiscoveryRequestReply
	1, // 4: scalezillapb.Scalezilla.ServiceNodePolling:output_type -> scalezillapb.ServiceNodePollingRequestReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scalezillapb_requests_proto_init() }
func file_scalezillapb_requests_proto_init() {
	if File_scalezillapb_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalezillapb_requests_proto_rawDesc), len(file_scalezillapb_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalezillapb_requests_proto_goTypes,
		DependencyIndexes: file_scalezillapb_requests_proto_depIdxs,
		MessageInfos:      file_scalezillapb_requests_proto_msgTypes,
	}.Build()
	File_scalezillapb_requests_proto = out.File
	file_scalezillapb_requests_proto_goTypes = nil
	file_scalezillapb_requests_proto_depIdxs = nil
}
